---

- name: create FireFoxDriver Directory
  file:
    path: /usr/local/sharecd/firefoxdriver
    state: directory
    owner: root
    group : root
    mode: 0755

- name: Download and extract ChromeDriver
  unarchive:
    src: https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
    dest: /usr/local/sharecd/firefoxdriver
    remote_src: True