---

- name: INSS Ubuntu Tools playbook
  hosts: localhost
  become: true
  roles:
  # All roles
    - { role: chrome }
    - { role: chromeDriverSelenium }
    - { role: firefoxDriverSelenium }
    - { role: java-jdk }
    - { role: jenkinsJobBuilder }
    - { role: JBToolBox }
    - { role: linuxTools }
    - { role: docker }
    - { role: npm }
    - { role: phantomJS }
    - { role: pythonTools }
    - { role: rDesktop }
    - { role: ruby }
    - { role: seleniumTools }
    - { role: slack }
    - { role: virtualbox }
    - { role: vagrant }
    - { role: vcloudTools }
    - { role: postgres }
    - { role: behave, tags: behave }
  vars:
    - google_apt_file: /etc/apt/sources.list.d/google-chrome.list
    - tmp_dir: /tmp/chromedriver