---

- name: INSS Ubuntu Tools playbook
  hosts: localhost
  roles:
  # All roles
    - { role: chrome, become: true }
    - { role: chromeDriverSelenium, become: true }
    - { role: docker, become: true }
    - { role: java-jdk, become: true }
    - { role: jenkinsJobBuilder, become: true }
    - { role: libreOffice, become: true }
    - { role: linuxTools, become: true }
    - { role: npm, become: true }
    - { role: phantomJS, become: true }
    - { role: pythonTools, become: true }
    - { role: rDesktop, become: true }
    - { role: ruby, become: true }
    - { role: seleniumTools, become: true }
    - { role: slack, become: true }
    - { role: terminator, become: true }
    - { role: vagrant, become: true }
    - { role: vcloudTools, become: true }
    - { role: virtualbox, become: true }