---

- name: create ChromeDriver Directory
  file:
    path: /usr/local/sharecd/chromedriver
    state: directory
    owner: root
    group : root
    mode: 0755

- name: Download and extract ChromeDriver
  unarchive:
    src: https://chromedriver.storage.googleapis.com/2.0/chromedriver_linux64.zip
    dest: /usr/local/sharecd/chromedriver
    remote_src: True