---

# Install pip
- name: install pip
  apt:
    name: python-pip
    state: latest

# Install Virtual Env
- name: install virtual env
  apt:
    name: virtualenv-clone
    state: latest

- name: install virtual env wrapper
  apt:
    name: virtualenvwrapper
    state: latest

