---

- name: Does the Google apt file exist?
  command: test -f {{google_apt_file}}
  register: google_apt_exists
  ignore_errors: True

- name: Add Google Chrome key
  shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  when: google_apt_exists.rc == 1

- name: Add Google Chrome repo
  copy: content="deb http://dl.google.com/linux/chrome/deb/ stable main" dest={{google_apt_file}} owner=root group=root mode=644
  when: google_apt_exists.rc == 1

- name: check if Google Chrome is installed
  stat: path=/usr/bin/google_chrome
  register: google_chrome

- name: Install Google Chrome
  apt: pkg=google-chrome-stable state=installed
  when: not google_chrome.stat.exists
