---

- name: add docker key
  apt_key:
          id=9DC858229FC7DD38854AE2D88D81803C0EBFCD88
          keyserver=https://download.docker.com/linux/ubuntu/gpg
          state=present

- name: add docker repository
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main'
                  filename='docker'
                  state=present

- name: install docker-engine
  apt: name=docker-engine
       state=present
       update_cache=yes

- name: Install docker-compose
  get_url: url="https://github.com/docker/compose/releases/download/1.9.0/docker-compose-Linux-x86_64" dest=/usr/local/bin/docker-compose force=no mode=0755