---

- name: add docker key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repository
  apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable'
                  filename='docker'
                  state=present

- name: install docker-ce
  apt: name=docker-ce
       state=present

- name: Install docker-compose
  get_url: url="https://github.com/docker/compose/releases/download/1.9.0/docker-compose-Linux-x86_64" dest=/usr/local/bin/docker-compose force=no mode=0755