---

- name: Ensure bash, OpenSSl, and libssl are the latest versions
  apt: name={{ item }} state=latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
  tags: packages

- name: Install PostgreSQL
  apt: name={{ item }} state=installed
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-psycopg2
  tags: packages

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

- name: ensure a postgres user is created
  postgresql_user: name=postgres password=manager
  sudo_user: postgres